language: python
matrix:
  include:
    - python: 2.7
    - python: 3.6
      dist: xenial
cache: pip
install:
  - pip install .
  - python setup.py -q install
script:
  - travis_wait 35 python -m unittest discover
