language: python
matrix:
  include:
    - python: 3.6
      dist: xenial
cache: pip
install:
  - pip install -r requirements.txt
  - pip install .
script:
  - travis_wait 35 python -m unittest discover
